# Project
mod_version=1.3.4
group=org.cyclops.integratedcrafting
java_version=21

# Common
minecraft_version=1.21.1
mod_name=IntegratedCrafting
mod_author=rubensworks (aka kroeser)
mod_id=integratedcrafting
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedCrafting
issue_tracker_url=https://github.com/CyclopsMC/IntegratedCrafting/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-crafting
description=Craft stuff in Integrated Dynamics networks.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

parchment_version=2024.07.07
parchment_minecraft_version=1.21
curseforge_project_id=287357
modrinth_project_id=qwpACdla

# NeoForge
neoforge_version=21.1.152
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/integrated-crafting.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Dependencies
cyclopscore_version=1.26.2-808
integrateddynamics_version=1.27.9-1316
commoncapabilities_version=2.9.12-263
integratedtunnels_version=1.8.44-484
