modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedCrafting/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-crafting"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedcrafting"
version="${file.jarVersion}"
displayName="IntegratedCrafting"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-crafting.json"
description='''
Craft stuff in Integrated Dynamics networks.
'''
[[dependencies.integratedcrafting]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.11.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.8.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.7.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,]"
    ordering="NONE"
    side="BOTH"
