modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedCrafting/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-crafting"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedcrafting"
version="${file.jarVersion}"
displayName="IntegratedCrafting"
description='''
Craft stuff in Integrated Dynamics networks.
'''
[[dependencies.integratedcrafting]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.9.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.1.15,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.5.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,]"
    ordering="NONE"
    side="BOTH"
