modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedCrafting/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-crafting"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedcrafting"
version="${file.jarVersion}"
displayName="IntegratedCrafting"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-crafting.json"
description='''
Craft stuff in Integrated Dynamics networks.
'''
[[dependencies.integratedcrafting]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="integrateddynamics"
    type="required"
    versionRange="[1.20.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="commoncapabilities"
    type="required"
    versionRange="[2.9.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,]"
    ordering="NONE"
    side="BOTH"
