modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedCrafting/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-crafting"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedcrafting"
version="${file.jarVersion}"
displayName="IntegratedCrafting"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-crafting.json"
description='''
Craft stuff in Integrated Dynamics networks.
'''
[[dependencies.integratedcrafting]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.17.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.11.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.8.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedcrafting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,]"
    ordering="NONE"
    side="BOTH"
